theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
cursorline = true
bufferline = "always"
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = false

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-p = ":clipboard-paste-after"
A-P = ":clipboard-paste-before"
A-R = ":clipboard-paste-replace"
A-y = ":clipboard-yank"
"C-pageup" = ":bnext"
"C-pagedown" = ":bprev"
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_end", "collapse_selection"]

[keys.insert]
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_end", "collapse_selection"]
